[build]
  base = "client"
  command = "./script/confgen production && npm run build"
  publish = "client/out"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"
